version: '3.9'

services:
  crud_db:
    container_name: crud_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrates/v1_migrate.sql:/docker-entrypoint-initdb.d/v1_migrate.sql
    command: [ "postgres", "-c", "fsync=off" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PRODUCTION: ${APP_PRODUCTION}
    ports:
      - "8080:8080"
    depends_on:
      crud_db:
        condition: service_healthy

volumes:
  pgdata: {}
