GET http://localhost:8080/healthy

###
GET http://localhost:8080/api/v1/product/list

###
POST http://localhost:8080/api/v1/product/create
Content-Type: application/json

{
    "name": "Notebook Dell",
    "description": "Notebook para testes aqui",
    "price": 3500
}